openapi: 3.0.0
info:
  title: API Faculdade
  version: 1.0.0
  description: Documentação da API com Swagger
servers:
  - url: http://localhost:3000
    description: Servidor Local
tags:
  - name: Users
    description: Operações relacionadas a usuários
  - name: Auth
    description: Operação de autenticação
security:
  - bearerAuth: []
paths:
  /users:
    get:
      tags:
        - Users
      summary: Retorna a lista de usuários
      responses:
        "200":
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserResponse"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erro interno do servidor"
    post:
      tags:
        - Users
      summary: Cria um novo usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "201":
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Dados inválidos"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erro interno do servidor"
  /users/{id}:
    get:
      tags:
        - Users
      summary: Retorna um usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: O ID do usuário a ser retornado
      responses:
        "200":
          description: Usuário retornado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuário não encontrado"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erro interno do servidor"
    put:
      tags:
        - Users
      summary: Atualiza todos os dados de um usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: O ID do usuário a ser atualizado
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "200":
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Dados inválidos"
        "404":
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuário não encontrado"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erro interno do servidor"
    patch:
      tags:
        - Users
      summary: Atualiza parcialmente um usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: O ID do usuário a ser atualizado
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "200":
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Dados inválidos"
        "404":
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuário não encontrado"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erro interno do servidor"
    delete:
      tags:
        - Users
      summary: Remove um usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: O ID do usuário a ser removido
      responses:
        "204":
          description: Usuário removido com sucesso
        "404":
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuário não encontrado"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erro interno do servidor"
  /login:
    post:
      tags:
        - Auth
      summary: Autentica um usuário e retorna um token JWT
      security: [] # Desabilita a autenticação para este endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: O email do usuário.
                password:
                  type: string
                  description: A senha do usuário.
              required:
                - email
                - password
              example:
                email: joao.silva@email.com
                password: senha123
      responses:
        200:
          description: Autenticação bem-sucedida
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Token JWT para autenticação.
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        401:
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Dados inválidos"
        500:
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erro interno do servidor"

components:
  schemas:
    UserResponse:
      type: object
      required:
        - nome
        - email
        - senha
      properties:
        id:
          type: string
          description: O ID gerado do usuário.
        nome:
          type: string
          description: O nome do usuário.
        email:
          type: string
          description: O email único do usuário.
        password:
          type: string
          description: A senha do usuário.
      example:
        id: "123"
        nome: João da Silva
        email: joao.silva@email.com
        password: senha123
    UserRequest:
      type: object
      required:
        - nome
        - email
        - password
      properties:
        nome:
          type: string
          description: O nome do usuário.
        email:
          type: string
          description: O email único do usuário.
        password:
          type: string
          description: A senha do usuário.
      example:
        nome: João da Silva
        email: joao.silva@email.com
        password: senha123
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
